services:
  - type: web
    name: graphmind-backend
    env: python
    rootDir: backend
    buildCommand: "pip install uv==0.7.12 && uv sync --frozen"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
