name: Deploy Backend to Production

on: 
  push:
    branches:
      - "main"
    paths:
      - "backend/**"

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install Dependencies
        run: |
          pip install uv==0.7.12
          uv sync --frozen
        working-directory: backend

      - name: Run Tests
        run: |
          uv run pytest tests/ -v