name: Deploy Frontend to Production

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: Install Dependencies
        working-directory: frontend
        run: |
          npm install

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm run build

      - name: Deploy to Vercel
        working-directory: frontend
        run: |
          npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}